In [61]:
import pandas as pd;

In [62]:
import numpy as np;

In [63]:
df=pd.read_csv("final.csv")

In [64]:
df.head()

,customerid,sessions_per_user,customerid.1,actions_per_user,customerid.2,avg_qty,user_flag
0,12427,1,12427,6,12427,6.0,low
1,12431,1,12431,6,12431,6.0,low
2,12433,1,12433,3,12433,3.0,low
3,12471,1,12471,24,12471,24.0,medium
4,12472,1,12472,24,12472,24.0,medium

In [65]:
df.tail()

,customerid,sessions_per_user,customerid.1,actions_per_user,customerid.2,avg_qty,user_flag
230,18144,1,18144,6,18144,6.0,low
231,18168,1,18168,6,18168,6.0,low
232,18225,1,18225,4,18225,4.0,low
233,18229,1,18229,6,18229,6.0,low
234,18239,1,18239,12,18239,12.0,medium

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         235 non-null    int64
 1   sessions_per_user  235 non-null    int64
 2   customerid.1       235 non-null    int64
 3   actions_per_user   235 non-null    int64
 4   customerid.2       235 non-null    int64
 5   avg_qty            235 non-null    float64
 6   user_flag          235 non-null    str
dtypes: float64(1), int64(5), str(1)
memory usage: 13.0 KB

In [70]:
df.columns

Index(['customerid', 'sessions_per_user', 'customerid.1', 'actions_per_user',
       'customerid.2', 'avg_qty', 'user_flag'],
      dtype='str')

In [76]:
df.describe()

,customerid,sessions_per_user,customerid.1,actions_per_user,customerid.2,avg_qty
count,235.000000,235.0,235.000000,235.000000,235.000000,235.000000
mean,15432.659574,1.0,15432.659574,9.212766,15432.659574,9.212766
std,1744.908832,0.0,1744.908832,18.915620,1744.908832,18.915620
min,12427.000000,1.0,12427.000000,1.000000,12427.000000,1.000000
25%,14046.000000,1.0,14046.000000,1.000000,14046.000000,1.000000
50%,15363.000000,1.0,15363.000000,3.000000,15363.000000,3.000000
75%,17006.000000,1.0,17006.000000,8.000000,17006.000000,8.000000
max,18239.000000,1.0,18239.000000,144.000000,18239.000000,144.000000

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         235 non-null    int64
 1   sessions_per_user  235 non-null    int64
 2   customerid.1       235 non-null    int64
 3   actions_per_user   235 non-null    int64
 4   customerid.2       235 non-null    int64
 5   avg_qty            235 non-null    float64
 6   user_flag          235 non-null    str
dtypes: float64(1), int64(5), str(1)
memory usage: 13.0 KB

In [88]:
df.isnull().sum()

customerid           0
sessions_per_user    0
customerid.1         0
actions_per_user     0
customerid.2         0
avg_qty              0
user_flag            0
dtype: int64

In [93]:
df=df.drop(['customerid.1', 'customerid.2'], axis=1)

In [94]:
df.isnull().sum()

customerid           0
sessions_per_user    0
actions_per_user     0
avg_qty              0
user_flag            0
dtype: int64

In [95]:
df.columns

Index(['customerid', 'sessions_per_user', 'actions_per_user', 'avg_qty',
       'user_flag'],
      dtype='str')

In [96]:
df.describe()

         customerid  sessions_per_user  actions_per_user     avg_qty
count    235.000000              235.0        235.000000  235.000000
mean   15432.659574                1.0          9.212766    9.212766
std     1744.908832                0.0         18.915620   18.915620
min    12427.000000                1.0          1.000000    1.000000
25%    14046.000000                1.0          1.000000    1.000000
50%    15363.000000                1.0          3.000000    3.000000
75%    17006.000000                1.0          8.000000    8.000000
max    18239.000000                1.0        144.000000  144.000000

In [97]:
lower_limit = df['actions_per_user'].quantile(0.10)
upper_limit = df['actions_per_user'].quantile(0.90)

In [98]:
print(lower_limit, upper_limit)

1.0 24.0

In [99]:
def activity(a):
    if a <= lower_limit:
        return 'low_activity'
    elif a >= upper_limit:
        return 'high_activity'
    else:
        return 'normal'

In [100]:
df['activity_status'] = df['actions_per_user'].apply(activity)

In [101]:
df['activity_status'].value_counts()

activity_status
normal           134
low_activity      74
high_activity     27
Name: count, dtype: int64

In [103]:
df.to_csv('final_user_activity.csv', index=False)